/** Declaration file generated by dts-gen */

export = vue_cropperjs;

declare const vue_cropperjs: {
    default: {
        methods: {
            clear: any;
            destroy: any;
            disable: any;
            enable: any;
            getCanvasData: any;
            getContainerData: any;
            getCropBoxData: any;
            getCroppedCanvas: any;
            getData: any;
            getImageData: any;
            initCrop: any;
            move: any;
            moveTo: any;
            relativeZoom: any;
            replace: any;
            reset: any;
            rotate: any;
            rotateTo: any;
            scale: any;
            scaleX: any;
            scaleY: any;
            setAspectRatio: any;
            setCanvasData: any;
            setCropBoxData: any;
            setData: any;
            setDragMode: any;
            zoomTo: any;
        };
        mounted: any;
        props: {
            alt: any;
            aspectRatio: any;
            autoCrop: {
                default: boolean;
                type: any;
            };
            autoCropArea: any;
            background: {
                default: boolean;
                type: any;
            };
            center: {
                default: boolean;
                type: any;
            };
            checkCrossOrigin: {
                default: boolean;
                type: any;
            };
            checkOrientation: {
                default: boolean;
                type: any;
            };
            containerStyle: any;
            crop: any;
            cropBoxMovable: {
                default: boolean;
                type: any;
            };
            cropBoxResizable: {
                default: boolean;
                type: any;
            };
            cropend: any;
            cropmove: any;
            cropstart: any;
            data: any;
            dragMode: any;
            guides: {
                default: boolean;
                type: any;
            };
            highlight: {
                default: boolean;
                type: any;
            };
            imgStyle: any;
            initialAspectRatio: any;
            minCanvasHeight: any;
            minCanvasWidth: any;
            minContainerHeight: any;
            minContainerWidth: any;
            minCropBoxHeight: any;
            minCropBoxWidth: any;
            modal: {
                default: boolean;
                type: any;
            };
            movable: {
                default: boolean;
                type: any;
            };
            preview: any[];
            ready: any;
            responsive: {
                default: boolean;
                type: any;
            };
            restore: {
                default: boolean;
                type: any;
            };
            rotatable: {
                default: boolean;
                type: any;
            };
            scalable: {
                default: boolean;
                type: any;
            };
            src: {
                default: string;
                type: any;
            };
            toggleDragModeOnDblclick: {
                default: boolean;
                type: any;
            };
            viewMode: any;
            wheelZoomRatio: any;
            zoom: any;
            zoomOnTouch: {
                default: boolean;
                type: any;
            };
            zoomOnWheel: {
                default: boolean;
                type: any;
            };
            zoomable: {
                default: boolean;
                type: any;
            };
        };
        render: any;
    };
};

